### ISSUE TITLE
Follower List Limited....

### ISSUE THREAD

**Issue by Cantide1** [lindstrm/Twitcher#4]
So the follower list is limited to what looks like 25 streams. The streams I get back don't seem to be that random (I haven't done too many tests) because I feel like I'm getting the same people every time. This would have to be investigated.

Some people (myself included) have over 100 people followed, by a lot. Somewhere close to 300 maybe. How would you go about sending multiple requests that didn't return all the same results each time? I don't know enough about the API to be able to answer this question for you.

I've talked to someone that made a similar program and he said that the twitch API only returns 25 live streams but that can be increased up to 100. Something worth looking into?

A thought: if you are getting different streams every time you poll twitch maybe you could just send multiple requests and populate the list with new streams every time, but over and over and eventually have everyone on that. That's super sloppy and risky though.

I edited the XML file directly and added every streamer I follow and they don't all show up. 
Which streams show up doesn't feel random because I get the same results most of the time.

Anyways...I LOVE your program and what it does so I really hope you continue to develop it. GG man. 

GG.

**Comment by lindstrm** [comment]
Thanks for the bug report.
I had no idea people, besides me, actually used it so I guess I have to look into it and continue the development.

As for the limit that was news to me since i'm not even anywhere near that amount :)

Just to clarify though, is it people you follow on your connected twitch account or in my app?

**Comment by Cantide1** [comment]
I'm not sure exactly what you are trying to ask, but inside the app the list is limited. The follower list is complete, but the number of streams that actually show up in the main view of the app is limited to 25. If you are more specific in your question I can give you a better answer I'm sorry! =x

**Comment by lindstrm** [comment]
Ok, well to make it easy for both of us could you paste the content of your config.twitch.xml on www.paster.se and give me the link? Don't forget to remove your username and accesstoken, if present.

**Comment by lindstrm** [comment]
Fixed in next release.
